# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positiveCertainty', models.DecimalField(decimal_places=20, max_digits=20, null=True)),
                ('negativeCertainty', models.DecimalField(decimal_places=20, max_digits=20, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos')),
            ],
        ),
    ]
