# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='certainty',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='negativeCertainty',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(null=True, upload_to='./'),
        ),
        migrations.AlterField(
            model_name='image',
            name='positiveCertainty',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
    ]
